/**
 * @file questions_data.h
 * @brief Auto-generated question bank from questions.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY. 
 * Any changes will be overwritten during the next build.
 */
#ifndef __QUESTIONS_DATA_H__
#define __QUESTIONS_DATA_H__

#include <stdint.h>

#define MAX_OPTIONS 4
#define MAX_QUESTION_LEN 128
#define MAX_OPTION_LEN 64

typedef struct {
    uint16_t id;
    char question[MAX_QUESTION_LEN];
    char options[MAX_OPTIONS][MAX_OPTION_LEN];
    uint8_t answerIndex;
    uint8_t timeLimitSec;
} Question_t;

extern const Question_t question_bank[3];
extern const uint16_t question_bank_size;

#endif // __QUESTIONS_DATA_H__
