import json
import os
import sys

def main():
    if len(sys.argv) != 4:
        print("Usage: generate_questions.py <input_json> <output_header> <output_source>")
        sys.exit(1)

    json_path = sys.argv[1]
    header_path = sys.argv[2]
    source_path = sys.argv[3]

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            questions = json.load(f)
    except Exception as e:
        print(f"Error reading {json_path}: {e}")
        sys.exit(1)

    num_questions = len(questions)

    # Ensure output directories exist
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    os.makedirs(os.path.dirname(source_path), exist_ok=True)

    header_content = f"""/**
 * @file questions_data.h
 * @brief Auto-generated question bank from {os.path.basename(json_path)}
 * 
 * DO NOT EDIT THIS FILE MANUALLY. 
 * Any changes will be overwritten during the next build.
 */
#ifndef __QUESTIONS_DATA_H__
#define __QUESTIONS_DATA_H__

#include <stdint.h>

#define MAX_OPTIONS 4
#define MAX_QUESTION_LEN 128
#define MAX_OPTION_LEN 64

typedef struct {{
    uint16_t id;
    char question[MAX_QUESTION_LEN];
    char options[MAX_OPTIONS][MAX_OPTION_LEN];
    uint8_t answerIndex;
    uint8_t timeLimitSec;
}} Question_t;

extern const Question_t question_bank[{num_questions}];
extern const uint16_t question_bank_size;

#endif // __QUESTIONS_DATA_H__
"""

    source_content = f"""/**
 * @file questions_data.c
 * @brief Auto-generated question bank from {os.path.basename(json_path)}
 * 
 * DO NOT EDIT THIS FILE MANUALLY. 
 * Any changes will be overwritten during the next build.
 */
#include "questions_data.h"

const uint16_t question_bank_size = {num_questions};

const Question_t question_bank[{num_questions}] = {{
"""

    for q in questions:
        q_id = q.get('id', 0)
        q_text = q.get('question', '').replace('"', '\\"')
        options = q.get('options', [])
        # Ensure exactly MAX_OPTIONS
        options_c = []
        for i in range(4):
            if i < len(options):
                opt = options[i].replace('"', '\\"')
                options_c.append(f'"{opt}"')
            else:
                options_c.append('""')
                
        answer_index = q.get('answerIndex', 0)
        time_limit = q.get('timeLimitSec', 15)

        source_content += f"""    {{
        .id = {q_id},
        .question = "{q_text}",
        .options = {{ {", ".join(options_c)} }},
        .answerIndex = {answer_index},
        .timeLimitSec = {time_limit}
    }},
"""

    source_content += "};\n"

    # Write header
    write_if_changed(header_path, header_content)
    
    # Write source
    write_if_changed(source_path, source_content)
    
    print(f"Successfully generated C question bank with {num_questions} questions.")

def write_if_changed(filepath, new_content):
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            old_content = f.read()
        if old_content == new_content:
            # No change, don't write to avoid modifying file timestamp
            # which could trigger unnecessary recompilation
            return
            
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)

if __name__ == "__main__":
    main()
